apiVersion: v1
kind: ConfigMap
metadata:
  name: html-content
  namespace: html-app
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <body style="background:#f44336; display:flex; align-items:center; justify-content:center; height:100vh; margin:0; font-family:sans-serif;">
        <h1 style="color:white; font-size:4rem;">💥 Version 2 — BROKEN!</h1>
      </body>
    </html>
